name: react deploy
on:
  push:
    branches:
      - main

jobs:
  My-Deploy-jobs:
    runs-on: ubuntu-latest
    env:
      REMOTE_DIR: /home/ubuntu/2025action

    steps:
      - name: ssh to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{env.REMOTE_DIR}}
            pwd
